version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: api-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - api-net

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - api-net
networks:
  api-net:
    driver: bridge